fragment GetToppingsFields on pizzaToppingConnection {
  topping {
    name
    price
    }
  defaultSelected
}

fragment GetPizzaFields on pizzaSize {
    name
    maxToppings
    basePrice
    toppings {
        ...GetToppingsFields
    }
}

query getPizza {
    pizzaSizes {
      ...GetPizzaFields
    }
}