fragment GetPizzaFields on pizzaSize {
    name
    maxToppings
    basePrice
    toppings {
        topping {
          name
          price
        }
        defaultSelected
    }
}

query getPizza {
    pizzaSizes {
      ...GetPizzaFields
    }
}